services:
  # The Python/Flask Backend API
  - type: web
    name: etep-api
    env: python
    region: oregon # or your preferred region
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: backend
    healthCheckPath: /api/health # A simple health check endpoint we'll add
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: GEMINI_API_KEY
        fromSecret: true # Set to true to use a secret from an environment group
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL # For CORS
        fromSecret: true 

  # The JavaScript Frontend PWA
  - type: static
    name: etep-frontend
    rootDir: frontend
    plan: free
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
      - frontend/**
