services:
  # The Python/Flask Backend API
  - type: web
    name: etep-api
    env: python
    runtime: python3
    region: oregon # or your preferred region
    plan: free # use a paid plan for better performance
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: GEMINI_API_KEY
        fromSecret: gemini_api_key # You will create this secret in Render's dashboard
      - key: FLASK_ENV
        value: production

  # The JavaScript Frontend PWA
  - type: web
    name: etep-frontend
    env: static
    region: oregon
    plan: free
    rootDir: frontend
    staticPublishPath: . # Serve from the root of the 'frontend' directory
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
      - frontend/**